# Generated by Django 4.2.21 on 2025-07-01 19:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0026_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_claimed_decimal', models.DecimalField(decimal_places=2, help_text="Quantity claimed in 'MasterUnits.IndividualItems' format (e.g., 1.05).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(help_text='Reason for the claim (e.g., Expired, Damaged).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_from_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_claims', to='stock.shop')),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='stock.productdetail')),
                ('retrieval_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_retrieved', to='stock.vehicle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Claim',
                'verbose_name_plural': 'Stock Claims',
                'ordering': ['-claim_date'],
            },
        ),
    ]
