# nixpacks.toml (Definitive Version)

# Tell Nixpacks to install both Python and Node.js environments
providers = ["python", "node"]

# --- Define the build and start commands ---

# This section defines the command that will be run when the application starts
[start]
cmd = "gunicorn gov_agency.wsgi:application --bind 0.0.0.0:$PORT"

# This section defines the commands that will be run during the build/install phase
[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt", 
    "npm install"
]

[phases.build]
cmds = [
    "npm run build", 
    "python manage.py collectstatic --no-input"
]