# nixpacks.toml

providers = ["python", "node"]

[phases.install]
cmds = [
    "pip install --upgrade pip", # Good practice to ensure pip is up to date
    "pip install -r requirements.txt", 
    "npm install"
]

[phases.build]
cmds = [
    "npm run build", 
    "python manage.py collectstatic --no-input"
]

[start]
# The path to your wsgi file is 'gov_agency.wsgi'
cmd = "gunicorn gov_agency.wsgi --bind 0.0.0.0:$PORT"