# nixpacks.toml (Corrected)

# Phase 1: Setup the environment
[phases.setup]
# List the specific packages needed. Nixpacks will handle the base system.
nixPkgs = ["python311", "nodejs-18_x"]

# Phase 2: Install dependencies
[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

# Phase 3: Build the application
[phases.build]
cmds = ["npm run build", "python manage.py collectstatic --no-input"]

# Phase 4: Define the start command
[start]
cmd = "gunicorn gov_agency.wsgi:application --bind 0.0.0.0:8000"