# Generated by Django 4.2.21 on 2025-06-28 16:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0019_alter_productdetail_expirey_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT_SALE', 'Credit from Sale'), ('CASH_RECEIPT', 'Cash Receipt'), ('OPENING_BALANCE', 'Opening Balance'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount the shop now owes you (e.g., from a credit sale). Increases balance.', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount the shop paid you (e.g., cash received). Decreases balance.', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='stock.shop')),
                ('source_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_ledger_entry', to='stock.salestransaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Financial Transaction',
                'verbose_name_plural': 'Shop Financial Transactions',
                'ordering': ['-transaction_date', '-pk'],
            },
        ),
    ]
