# Generated by Django 4.2.21 on 2025-06-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_alter_productdetail_expirey_date'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfinancialtransaction',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, help_text='Customer name for this transaction, if not a registered shop.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopfinancialtransaction',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='The registered shop this transaction belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='stock.shop'),
        ),
    ]
