# Generated by Django 4.2.21 on 2025-07-03 23:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_shopfinancialtransaction_customer_name_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(help_text="Name of the person, expense, or entity for this transaction (e.g., 'Office Supplies', 'John Doe - Loan').", max_length=200)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount owed TO you by this entity.', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid BY you to this entity.', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Financial Transaction',
                'verbose_name_plural': 'Custom Financial Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
