# Generated by Django 4.2.21 on 2025-07-05 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_dailysummary_cash_given_as_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='net_cash_in_hand',
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='net_physical_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net for physical cash only: (CASH Sales + Credit Payments) - Expenses.', max_digits=14),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='net_total_settlement',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net including online: (CASH+ONLINE Sales + Credit Payments) - Expenses.', max_digits=14),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='online_sales_today',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
