# Generated by Django 4.2.21 on 2025-07-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_dailysummary_net_cash_in_hand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysummary',
            old_name='credit_sales_today',
            new_name='total_debit_today',
        ),
    ]
