# Generated by Django 4.2.21 on 2025-07-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_credit_sales_today_dailysummary_total_debit_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='summary_date',
            field=models.DateField(help_text='The specific date this summary represents.'),
        ),
    ]
