# Generated by Django 4.2.21 on 2025-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dailysummary_summary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccounttransaction',
            name='store_in_daily_summery',
            field=models.BooleanField(default=False, help_text="Check 'Yes' if this transaction is a business expense."),
        ),
    ]
