# Generated by Django 4.2.21 on 2025-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customaccounttransaction_store_in_daily_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccounttransaction',
            name='store_in_daily_summery',
            field=models.BooleanField(default=False),
        ),
    ]
