# Generated by Django 4.2.21 on 2025-08-06 07:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customaccounttransaction_store_in_daily_summery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfinancialtransaction',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount the shop paid you (e.g., cash received).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shopfinancialtransaction',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount the shop now owes you (e.g., from a credit sale).', max_digits=12),
        ),
    ]
