# Generated by Django 4.2.21 on 2025-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_shopfinancialtransaction_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfinancialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT_SALE', 'Credit from Sale'), ('CASH_RECEIPT', 'Cash Receipt'), ('OPENING_BALANCE', 'Opening Balance'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('ONLINE', 'Online Payment')], max_length=20),
        ),
    ]
