# Generated by Django 4.2.21 on 2025-08-14 13:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_shopfinancialtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='online_received_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='shopfinancialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT_SALE', 'Credit from Sale'), ('CASH_RECEIPT', 'Cash Receipt'), ('ONLINE', 'Online Payment'), ('OPENING_BALANCE', 'Opening Balance')], max_length=20),
        ),
    ]
