# Generated by Django 4.2.21 on 2025-09-15 08:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_dailysummary_online_received_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfinancialtransaction',
            name='get_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
