# Generated by Django 4.2.21 on 2025-09-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_shopfinancialtransaction_get_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopfinancialtransaction',
            old_name='get_balance',
            new_name='balance',
        ),
    ]
