# Generated by Django 4.2.21 on 2025-09-19 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_get_balance_shopfinancialtransaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccounttransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
