# Generated by Django 4.2.21 on 2025-06-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_productdetail_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
