# Generated by Django 4.2.21 on 2025-06-09 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_productdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
