# Generated by Django 4.2.21 on 2025-06-09 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_productdetail_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='price_per_item',
            field=models.DecimalField(decimal_places=1, help_text='Price for one individual item (e.g., one bottle, one piece).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
