# Generated by Django 4.2.21 on 2025-06-13 09:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_productdetail_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 7, 13)),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_per_item',
            field=models.DecimalField(decimal_places=1, help_text='Price for one individual item (e.g., one bottle, one piece).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
