# Generated by Django 4.2.21 on 2025-06-16 18:32

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0009_alter_productdetail_price_per_item_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 7, 16)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_detail_snapshot',
            field=models.ForeignKey(help_text='The specific product detail (batch) that was sold.', on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='stock.productdetail'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_items_sold',
            field=models.DecimalField(decimal_places=1, help_text="Quantity sold in 'master_unit.item' format (e.g., 1.1 for 1 carton and 1 item).", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='e.g., ABC-123 or S1234XYZ', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('OTHER', 'Other')], default='TRUCK', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Vehicle capacity in kilograms', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this vehicle currently in service?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
