# Generated by Django 4.2.21 on 2025-06-19 18:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_time']},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_cost',
            new_name='total_cost_dispatch',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_revenue',
            new_name='total_revenue_dispatch',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='name_of_customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_items_sold',
        ),
        migrations.AddField(
            model_name='sale',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='stock.vehicle'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name_manual',
            field=models.CharField(blank=True, help_text='Customer name if not a registered shop.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_shop',
            field=models.ForeignKey(blank=True, help_text='The shop that made the purchase, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='stock.shop'),
        ),
        migrations.AddField(
            model_name='sale',
            name='needs_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash on Hand'), ('ONLINE', 'Online Transfer'), ('CREDIT', 'Credit/Account')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_sold_decimal',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text="Quantity dispatched in 'master_unit.item' format.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='returned_stock_decimal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Quantity returned by customer in 'master_unit.item' format.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING_DELIVERY', 'Pending Delivery'), ('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('FULLY_RETURNED', 'Fully Returned'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
