# Generated by Django 4.2.21 on 2025-06-22 10:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0017_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name_manual', models.CharField(blank=True, help_text="Customer's name if not selecting a registered shop.", max_length=200, null=True)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash on Hand'), ('ONLINE', 'Online Transfer'), ('CREDIT', 'Credit/Account')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_ITEMS', 'Pending Items'), ('PENDING_DELIVERY', 'Pending Delivery'), ('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('FULLY_RETURNED', 'Fully Returned'), ('CANCELLED', 'Cancelled')], default='PENDING_ITEMS', max_length=20)),
                ('needs_vehicle', models.BooleanField(default=False)),
                ('grand_total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='General notes for this entire transaction.', null=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_transactions', to='stock.vehicle')),
                ('customer_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_sales_transactions', to='stock.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_sales_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Transaction',
                'verbose_name_plural': 'Sales Transactions',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold_decimal', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('selling_price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price_per_item_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date_at_sale', models.DateField()),
                ('items_per_master_unit_at_sale', models.PositiveIntegerField()),
                ('total_item_dispatched_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item_dispatched_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returned_quantity_decimal', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('product_detail_snapshot', models.ForeignKey(help_text='The specific product batch (product name, expiry, etc.) sold.', on_delete=django.db.models.deletion.PROTECT, to='stock.productdetail')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.salestransaction')),
            ],
            options={
                'verbose_name': 'Sales Transaction Item',
                'verbose_name_plural': 'Sales Transaction Items',
                'ordering': ['pk'],
            },
        ),
    ]
