# Generated by Django 4.2.21 on 2025-06-28 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_salestransaction_salestransactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 7, 28)),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash on Hand'), ('ONLINE', 'Online Transfer'), ('CREDIT', 'Credit')], default='CASH', max_length=20),
        ),
    ]
