# Generated by Django 4.2.21 on 2025-06-29 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_productdetail_expirey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 7, 29)),
        ),
    ]
