# Generated by Django 4.2.21 on 2025-06-30 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['product_base__name', '-expirey_date'], 'verbose_name': 'Product Detail/Batch', 'verbose_name_plural': 'Product Details/Batches'},
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='total_items_in_stock',
            field=models.PositiveIntegerField(default=0, help_text='Total number of individual items currently in stock (e.g., 27 bottles).'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='items_per_master_unit',
            field=models.PositiveIntegerField(help_text='e.g., 6, 10, 12, or 24 bottles per Carton/Case.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='packing_type',
            field=models.CharField(default='Carton', help_text='e.g., Bottle, Box, Carton', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, help_text='Price for one individual item (e.g., one bottle).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity_in_packing',
            field=models.DecimalField(decimal_places=2, help_text='e.g., 1 (for 1 liter bottle), 0.5 (for 500ml)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='unit_of_measure',
            field=models.CharField(default='liter', help_text='e.g., kg, liter, pieces', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('product_base', 'packing_type', 'quantity_in_packing', 'unit_of_measure', 'expirey_date')},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='stock',
        ),
    ]
