# Generated by Django 4.2.21 on 2025-06-30 19:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_productdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['product_base__name', '-created_at'], 'verbose_name': 'Product Detail/Variant', 'verbose_name_plural': 'Product Details/Variants'},
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='stock',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 7, 31)),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='items_per_master_unit',
            field=models.PositiveIntegerField(help_text='e.g., Number of bottles per PET/Carton, or items per box.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='packing_type',
            field=models.CharField(default='Carton', help_text='e.g., Bottle, Box, Carton, PET Jar', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, help_text='Price for one individual item (e.g., one bottle, one piece).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity_in_packing',
            field=models.DecimalField(decimal_places=2, help_text='e.g., 1 (for 1 liter bottle), 0.5 (for 500ml), 12 (for a dozen items)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='unit_of_measure',
            field=models.CharField(default='liter', help_text='e.g., kg, liter, pieces, meters', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('product_base', 'packing_type', 'quantity_in_packing', 'unit_of_measure', 'expirey_date', 'stock')},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='total_items_in_stock',
        ),
    ]
