# Generated by Django 4.2.21 on 2025-06-30 21:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_alter_productdetail_price_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransactionitem',
            name='product_detail_snapshot',
            field=models.ForeignKey(help_text='The specific product batch (product name, expiry, etc.) sold.', on_delete=django.db.models.deletion.CASCADE, to='stock.productdetail'),
        ),
        migrations.AlterField(
            model_name='salestransactionitem',
            name='quantity_sold_decimal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='salestransactionitem',
            name='returned_quantity_decimal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
