# Generated by Django 4.2.21 on 2025-07-01 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_alter_salestransactionitem_product_detail_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 8, 1)),
        ),
    ]
