# Generated by Django 4.2.21 on 2025-07-04 14:11

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactionitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for this item (e.g., 5 for 5%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 8, 3)),
        ),
    ]
