# Generated by Django 4.2.21 on 2025-07-07 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_alter_productdetail_expirey_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransactionitem',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="A fixed monetary discount amount applied to the entire transaction's subtotal.", max_digits=10),
        ),
    ]
