# Generated by Django 4.2.21 on 2025-07-07 23:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_alter_salestransactionitem_product_detail_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransactionitem',
            name='returned_quantity_decimal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
