# Generated by Django 4.2.21 on 2025-07-08 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_alter_salestransactionitem_returned_quantity_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 8, 8)),
        ),
    ]
