# Generated by Django 4.2.21 on 2025-07-10 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='items_per_master_unit',
            field=models.PositiveIntegerField(help_text='e.g., Number of bottles per Carton/Pet', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='packing_type',
            field=models.CharField(default='Carton', help_text='e.g., Bottle, Box, Carton, PET', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity_in_packing',
            field=models.DecimalField(decimal_places=2, help_text='e.g., 1 (for 1 liter bottle), 0.5 (for 500ml)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.DecimalField(decimal_places=2, help_text='e.g. 100.00 for 100,', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='unit_of_measure',
            field=models.CharField(default='ML', help_text='e.g., kg, liter, pieces, ML', max_length=50),
        ),
    ]
