# Generated by Django 4.2.21 on 2025-07-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='status',
            field=models.CharField(choices=[('PENDING_ITEMS', 'Pending Items'), ('PENDING_DELIVERY', 'Pending Delivery'), ('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Returned'), ('FULLY_RETURNED', 'Fully Returned'), ('CANCELLED', 'Cancelled')], default='PENDING_ITEMS', max_length=20),
        ),
    ]
