# Generated by Django 4.2.21 on 2025-07-29 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_alter_salestransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 8, 28)),
        ),
        migrations.AddConstraint(
            model_name='addproduct',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_product_per_user'),
        ),
    ]
