# Generated by Django 4.2.21 on 2025-08-02 15:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_alter_productdetail_expirey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='amount_on_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='amount_paid_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='amount_paid_online',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash on Hand'), ('ONLINE', 'Online Transfer'), ('CREDIT', 'Credit'), ('SPLIT', 'Split Payment')], default='CASH', max_length=20),
        ),
    ]
