# Generated by Django 4.2.21 on 2025-08-03 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_salestransaction_amount_on_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 9, 2)),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_on_credit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_paid_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_paid_online',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
