# Generated by Django 4.2.21 on 2025-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_alter_productdetail_expirey_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_on_credit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_paid_cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='amount_paid_online',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
