# Generated by Django 4.2.21 on 2025-08-06 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_alter_salestransaction_amount_on_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='is_ready_for_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 9, 5)),
        ),
    ]
