# Generated by Django 4.2.21 on 2025-08-06 12:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_salestransaction_is_ready_for_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactionitem',
            name='increased_demand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional demand beyond dispatched quantity.', max_digits=10),
        ),
    ]
