# Generated by Django 4.2.21 on 2025-08-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0050_alter_productdetail_expirey_date_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='quantity_changed',
            new_name='quantity_change',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, max_digits=10,blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, max_digits=10,blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='action',
            field=models.CharField(choices=[('ADD', 'Stock Added'), ('CREATED', 'Product Created')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
