# Generated by Django 4.2.21 on 2025-08-10 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0052_alter_stockhistory_stock_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity_change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
