# Generated by Django 4.2.21 on 2025-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_alter_stockhistory_quantity_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='stock_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='stock_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
