# Generated by Django 4.2.21 on 2025-08-10 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0054_alter_stockhistory_quantity_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='performed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
