# Generated by Django 4.2.21 on 2025-08-10 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0055_stockhistory_user_alter_stockhistory_performed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_history_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
