# Generated by Django 4.2.21 on 2025-08-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0056_alter_stockhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
