# Generated by Django 4.2.21 on 2025-08-12 04:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0058_stockhistory_user_alter_stockhistory_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='selling_price_of_item',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling Price of an Item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 9, 11)),
        ),
    ]
