# Generated by Django 4.2.21 on 2025-08-14 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_productdetail_selling_price_of_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='expirey_date',
            field=models.DateField(default=datetime.date(2025, 9, 13)),
        ),
    ]
