# Generated by Django 4.2.21 on 2025-07-11 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='monthly_sales_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text="User's personal monthly sales revenue target.", max_digits=14),
        ),
    ]
