# Generated by Django 4.2.21 on 2025-07-11 18:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_agency', '0002_adminprofile_monthly_sales_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='monthly_sales_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text="User's personal monthly sales revenue target.", max_digits=14),
        ),
    ]
