# Generated by Django 4.2.21 on 2025-07-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov_agency', '0003_alter_adminprofile_monthly_sales_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='monthly_sales_target',
        ),
    ]
