# Generated by Django 4.2.21 on 2025-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_agency', '0004_remove_adminprofile_monthly_sales_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
